version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "3000:3000"
    depends_on:
      - tracker
      - file-manager

  tracker:
    build: ./tracker
    ports:
      - "3001:3001"

  file-manager:
    build: ./file-manager
    ports:
      - "3002:3002"
